### ISSUE TITLE
Allow Nullable types

### ISSUE THREAD

**Issue by michael-wolfenden** [ConfigInjectorContributors/ConfigInjector#11]
We often have configuration settings that are optional (have a blank setting value), however ConfigInjector fails when trying to cast from a string to a nullable.

For example:

``` xml
<add key="NullableIntSetting" value=""/>
<add key="NullableGuidSetting" value=""/>
```

``` csharp
public class NullableGuidSetting : ConfigurationSetting<Guid?>
{
}

public class NullableIntSetting : ConfigurationSetting<int?>
{
}
```

**Comment by uglybugger** [comment]
Resolved by d5be011d084b7bca436a82acc175869fa773a608. Thank you :)
