### ISSUE TITLE
bin/obj files in source control

### ISSUE THREAD

**Issue by becdetat** [ConfigInjectorContributors/ConfigInjector#17]
Looks like a pile of obj/bin files have got into source control, eg:

https://github.com/uglybugger/ConfigInjector/tree/master/src/ConfigInjector/bin/Debug

**Comment by uglybugger** [comment]
Argh. Not cool. Thanks for the heads-up.

On Thursday, 5 March 2015, Ben Scott notifications@github.com wrote:

> Looks like a pile of obj/bin files have got into source control, eg:
> 
> https://github.com/uglybugger/ConfigInjector/tree/master/src/ConfigInjector/bin/Debug
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/uglybugger/ConfigInjector/issues/17.

## 

http://www.customsig.com/Signature/Link/andrewh%40uglybugger.org

**Comment by uglybugger** [comment]
Fixed (finally) in b51494e.
